#!/usr/bin/env bash
# Declaratively apply ./secrets.json onto a computer box.
#
# Reads the manifest, resolves each env entry across bw / laptop env / fallback,
# renders a `shell.zsh` env file plus any declared raw files, and pushes them to
# the box via `computer sync`. New shells on the box pick up the env by sourcing
# ~/.config/secrets/shell.zsh (wired in home/zsh.nix).
set -euo pipefail

handle="${1:?usage: secrets-apply.sh <handle> [manifest] [force]}"
manifest="${2:-secrets.json}"
# mode is accepted for justfile symmetry with repos; currently unused because
# secrets apply is already idempotent (rewrites files with fixed dest paths).
_mode="${3:-}"

if [[ ! -f "$manifest" ]]; then
  echo "no manifest at $manifest — run 'just secrets-init' first" >&2
  exit 1
fi

if ! command -v jq >/dev/null; then
  echo "jq is required" >&2; exit 1
fi

# ------------------------------------------------------------------------------
# Bitwarden: unlock if the manifest references it.
# ------------------------------------------------------------------------------
bw_folder="$(jq -r '.bitwarden.folder // ""' "$manifest")"
has_bw_refs="$(jq -r '[.env[]?|select(.bw)]|length' "$manifest")"
bw_available=0

if [[ -n "$bw_folder" && "$has_bw_refs" -gt 0 ]]; then
  if ! command -v bw >/dev/null; then
    echo "bw CLI required for manifest with bitwarden refs; install with: brew install bitwarden-cli" >&2
    exit 1
  fi
  case "$(bw status | jq -r '.status')" in
    unauthenticated) echo "bw: not logged in. run: bw login" >&2; exit 1 ;;
    locked)
      BW_SESSION="$(bw unlock --raw)"
      export BW_SESSION
      ;;
    unlocked) : ;;
  esac
  bw_available=1
fi

# Cache the folder's items once so we don't hammer bw with repeated lookups.
declare -A BW_BY_NAME=()
if [[ "$bw_available" -eq 1 ]]; then
  folder_id="$(bw list folders | jq -r --arg n "$bw_folder" '.[]|select(.name==$n)|.id')"
  if [[ -z "$folder_id" || "$folder_id" == "null" ]]; then
    echo "bw folder not found: $bw_folder" >&2; exit 1
  fi
  while IFS=$'\t' read -r name item_json; do
    BW_BY_NAME["$name"]="$item_json"
  done < <(bw list items --folderid "$folder_id" | jq -rc '.[] | [.name, tostring] | @tsv')
fi

# ------------------------------------------------------------------------------
# Resolve one env entry. Prints the resolved value on stdout, or nothing if
# unresolved. Returns 0 if resolved, 1 otherwise.
# ------------------------------------------------------------------------------
resolve_env() {
  local var_name="$1" spec="$2"
  local bw_item env_name fallback field
  bw_item="$(jq -r '.bw // empty' <<<"$spec")"
  env_name="$(jq -r '.envName // empty' <<<"$spec")"
  fallback="$(jq -r '.fallback // empty' <<<"$spec")"
  field="$(jq -r '.field // "password"' <<<"$spec")"

  # 1. Bitwarden
  if [[ -n "$bw_item" && "$bw_available" -eq 1 && -n "${BW_BY_NAME[$bw_item]+x}" ]]; then
    local item="${BW_BY_NAME[$bw_item]}"
    local val=""
    case "$field" in
      password|username|totp|uri)
        val="$(jq -r --arg f "$field" '.login[$f] // empty' <<<"$item")" ;;
      notes)
        val="$(jq -r '.notes // empty' <<<"$item")" ;;
      *) # custom field
        val="$(jq -r --arg f "$field" '(.fields // [])[]|select(.name==$f)|.value' <<<"$item" | head -n1)" ;;
    esac
    if [[ -n "$val" && "$val" != "null" ]]; then
      printf '%s' "$val"; return 0
    fi
  fi

  # 2. laptop env
  if [[ -n "$env_name" && -n "${!env_name-}" ]]; then
    printf '%s' "${!env_name}"; return 0
  fi
  if [[ -n "${!var_name-}" ]]; then
    printf '%s' "${!var_name}"; return 0
  fi

  # 3. fallback resolvers
  case "$fallback" in
    gh-cli)
      if command -v gh >/dev/null && gh auth status >/dev/null 2>&1; then
        local tok; tok="$(gh auth token 2>/dev/null || true)"
        if [[ -n "$tok" ]]; then printf '%s' "$tok"; return 0; fi
      fi ;;
  esac

  return 1
}

# ------------------------------------------------------------------------------
# Render env file
# ------------------------------------------------------------------------------
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
env_file="$tmp/shell.zsh"
{
  printf '# Auto-generated by computer-nix secrets-apply. Sourced by zsh on every shell start.\n'
  printf '# Do not edit by hand; re-run `just secrets %s` to regenerate.\n\n' "$handle"
} >"$env_file"

resolved=0 missing=0
while IFS=$'\t' read -r var_name spec; do
  [[ -z "$var_name" ]] && continue
  if value="$(resolve_env "$var_name" "$spec")"; then
    printf 'export %s=%q\n' "$var_name" "$value" >>"$env_file"
    resolved=$((resolved+1))
    echo "  ✓ $var_name"
  else
    echo "  ✗ $var_name (unresolved)" >&2
    missing=$((missing+1))
  fi
done < <(jq -r '.env // {} | to_entries[] | [.key, (.value|tostring)] | @tsv' "$manifest")

# ------------------------------------------------------------------------------
# Push env file
# ------------------------------------------------------------------------------
if [[ "$resolved" -gt 0 ]]; then
  echo "==> pushing env ($resolved vars) to $handle:~/.config/secrets/shell.zsh"
  computer ssh "$handle" -- 'mkdir -p ~/.config/secrets && chmod 700 ~/.config/secrets' >/dev/null
  computer sync "$env_file" --computer "$handle" >/dev/null
  computer ssh "$handle" -- '
    set -e
    mv ~/shell.zsh ~/.config/secrets/shell.zsh
    chmod 600 ~/.config/secrets/shell.zsh
  ' >/dev/null
fi

# ------------------------------------------------------------------------------
# Raw files
# ------------------------------------------------------------------------------
files_count="$(jq -r '.files // [] | length' "$manifest")"
if [[ "$files_count" -gt 0 ]]; then
  echo "==> pushing $files_count file(s)"
  # Single jq pass → TSV; matches the pattern used in repos-apply.sh.
  while IFS=$'\t' read -r src dest mode; do
    [[ -z "$src" ]] && continue
    src_expanded="${src/#\~/$HOME}"

    if [[ ! -e "$src_expanded" ]]; then
      echo "  ✗ $src (not found on laptop, skipping)" >&2
      continue
    fi

    dest_dir="$(dirname "$dest")"
    name="${src_expanded##*/}"

    computer ssh "$handle" -- "mkdir -p ${dest_dir/#\~/\$HOME}" >/dev/null
    computer sync "$src_expanded" --computer "$handle" >/dev/null
    # computer sync drops into /home/node/; move to final path + chmod.
    computer ssh "$handle" -- "
      set -e
      mv ~/${name} ${dest/#\~/\$HOME}
      chmod ${mode} ${dest/#\~/\$HOME}
    " >/dev/null
    echo "  ✓ $src -> $handle:$dest"
  done < <(jq -r '.files // [] | .[] | [.src, .dest, (.mode // "0600")] | @tsv' "$manifest")
fi

if [[ "$missing" -gt 0 ]]; then
  echo
  echo "==> $missing secret(s) unresolved. They are referenced in $manifest but were not found in bw/env/fallback." >&2
fi
echo "==> done. new shells on $handle will source ~/.config/secrets/shell.zsh"
